### ISSUE TITLE
TeV spectrum

### ISSUE THREAD

**Issue by MariiaDrozdova** [anaderi/gamma-bins#1]
Сейчас не очень понятно, как сравнивать спектры по данными из каталога TeV. Ситуация там примерно в следующем:

в колонке **sed_dnde** содержится спектр
в колонке **sed_e_ref** содержится среднее значение диапазона частот, на которой померен поток из **sed_dnde**
колонка **spec_dnde_1TeV** дает значение на энергии 1TeV, если огибать спектр экпонентой

Стоит поизучать эти и другие колонки TeV, и что-нибудь придумать. (Интерполировать кривой, чтобы получить спектры в одинаковых диапазонах как в GeV ? )

**Comment by MariiaDrozdova** [comment]
https://github.com/anaderi/gamma-bins/blob/master/TeV_spectrum.ipynb
вот тут небольшая визуализация выше сказанного

**Comment by anaderi** [comment]
Well done!
